#!/usr/bin/env python3
"""
scp_aircraft.py - SCP (SCvx-style) for a 3-DOF point-mass fixed-wing aircraft
on environments generated by envgen.py.

--------------------------------------------------------------------------
Aircraft model
--------------------------------------------------------------------------
State   x = (px, py, pz, V, gamma, chi)   position [m], airspeed [m/s],
                                          flight-path angle, heading [rad]
Control u = (T, n_v, n_h)                 thrust [N], load factor components
                                          in the vertical / horizontal plane
                                          (n = sqrt(n_v^2 + n_h^2), bank = atan2(n_h, n_v))

    px'    = V cos(gamma) cos(chi)
    py'    = V cos(gamma) sin(chi)
    pz'    = V sin(gamma)
    V'     = (T - D) / m - g sin(gamma)
    gamma' = g (n_v - cos(gamma)) / V
    chi'   = g n_h / (V cos(gamma))

    D = q S C_D0 + K (n m g)^2 / (q S),   q = rho V^2 / 2   (parabolic drag polar)

Using load factor components instead of (C_L, bank) keeps most limits convex:
    0 <= T <= T_MAX                                  (linear)
    ||(n_v, n_h)||_2 <= N_MAX                        (second-order cone)
    |n_h| <= tan(BANK_MAX) n_v                       (linear, also forces n_v >= 0)
    V_MIN <= V <= V_MAX,  |gamma| <= GAMMA_MAX       (linear state bounds)
    ||(n_v, n_h)||_2 <= c_stall V^2                  (lift <= C_L_MAX; nonconvex)
The stall constraint is linearized as c_stall (2 V_bar V - V_bar^2), which
underestimates V^2, so the linearized constraint is conservative.

--------------------------------------------------------------------------
SCP formulation
--------------------------------------------------------------------------
Free final time: t = sigma * tau with tau in [0, 1]; sigma (flight time) is a
decision variable. Controls are first-order hold (linear between nodes).

Each iteration:
  * Propagates the nonlinear dynamics over every interval from the reference
    nodes (multiple shooting, RK4) together with the sensitivities of the end
    state to x_k, u_k, u_{k+1} and sigma. This gives the linearized dynamics
        x_{k+1} = x_prop + Phi dx_k + Bm du_k + Bp du_{k+1} + S dsigma + nu_k
    where nu_k is a virtual control (penalized) so the subproblem is never
    infeasible because of a poor linearization.
  * Obstacle constraints are enforced at every RK4 substep inside each
    interval (not just the nodes), using the same sensitivities to express
    each intermediate position as an affine function of the variables.
  * Solves the convex subproblem with a trust region; accepts or rejects via
    the SCvx ratio test on the nonlinear merit function
        J = cost + LAMBDA_DYN * sum ||defects / x_scale||_1
                 + LAMBDA_OBS * sum (obstacle violations / POS_SCALE)
    Both penalties are on scaled quantities, so a metre of dynamics error and a
    metre of obstacle intrusion cost the same order of magnitude.

Boundary conditions: start at the environment's start position, level
flight at V_CRUISE, heading toward the goal; end at the goal position
(speed, heading free within limits). The environment's start/goal
velocities are ignored.

Cost: W_TIME * flight time + W_SMOOTH * sum ||(u_{k+1} - u_k) / u_scale||^2.

Environments must be at aircraft scale. For the default airframe (turn
radius about 13 m) try:
    python envgen.py --size 400 400 120 --vehicle-radius 1 --margin 2 \
                     --occupancy 0.02 0.10 --n 20 --out envs_aircraft.json

Usage
    python scp_aircraft.py --envs c172_envs.json          # solve all
    python scp_aircraft.py --envs c172_envs.json --show 0 # plot a saved plan
"""
from __future__ import annotations

import argparse
import json
import time
import warnings
from dataclasses import dataclass, field

import cvxpy as cp
import numpy as np
import scipy.sparse as sp

from envgen import Environment, load_environments, save_environments


# ==========================================================================
# USER SETTINGS
# ==========================================================================

# ---- files ---------------------------------------------------------------
ENV_FILE          = "c172_envs.json"       # same default as jsbsim_c172.py
RESULTS_FILE      = "scp_aircraft_results.json"
FEASIBLE_FILE     = "feasible_envs_aircraft.json"
MAX_ENVS          = None                 # solve only the first N (None = all)
PLOT_INDEX        = None                 # plot this environment's result
VERBOSE           = False

# ---- airframe -------------------------------------------------------------
# If AIRFRAME_FILE exists, its values override the airframe and scale
# settings below (e.g. the Cessna 172 file written by
# `python jsbsim_c172.py calibrate`). Otherwise the generic UAV below is used.
AIRFRAME_FILE     = "c172_params.json"

MASS              = 3.0                  # kg
WING_AREA         = 0.5                  # m^2
RHO               = 1.225                # air density, kg/m^3
C_D0              = 0.03                 # zero-lift drag coefficient
K_INDUCED         = 0.05                 # induced drag factor, 1/(pi e AR)
C_L_MAX           = 1.2                  # maximum lift coefficient (stall)
T_MAX             = 15.0                 # N, available thrust at V = 0 (intercept)
THRUST_SLOPE      = 0.0                  # N per m/s: available thrust = T_MAX + THRUST_SLOPE * V
THRUST_PLAN_FRACTION = 1.0               # plan with this share of available thrust
V_MIN             = 11.0                 # m/s (about 1.2x stall speed)
V_MAX             = 25.0                 # m/s
V_CRUISE          = 15.0                 # m/s, initial speed and guess speed
N_MAX             = 2.5                  # maximum load factor
BANK_MAX_DEG      = 60.0
GAMMA_MAX_DEG     = 20.0                 # climb / descent angle limit
N_V_RATE_MAX      = None                 # max rate of change of n_v, 1/s (None = no limit)
N_H_RATE_MAX      = None                 # max rate of change of n_h, 1/s (roll-rate proxy)
GRAVITY           = 9.81
FINAL_LEVEL       = False                # require gamma = 0 at the goal

# ---- discretization ------------------------------------------------------
N_NODES           = 40
RK4_STEPS         = 6                    # integration substeps per interval;
                                         #   obstacles are checked at each one
SIGMA_BOUNDS      = (1.0, 3600.0)        # flight time bounds, s

# ---- cost ------------------------------------------------------------------
W_TIME            = 1.0                  # per second of flight time
W_SPEED           = 0.0                  # on mean ((V - V_CRUISE) / V_CRUISE)^2
W_SMOOTH          = 1.0                  # on sum ||(u_{k+1} - u_k) / u_scale||^2

# ---- SCP algorithm ---------------------------------------------------------
# "ptr":  penalized trust region - the step size is penalized in the cost
#         (W_TRUST * ||dz||^2) and every step is accepted. Usually converges
#         faster and more smoothly.
# "scvx": hard trust region |dz| <= eta, with accept/reject ratio test.
ALGORITHM         = "ptr"
W_TRUST           = 1.0                  # ptr: weight on the squared scaled step
TRUST_CAP         = 0.5                  # ptr: hard cap on the scaled step

# ---- SCvx parameters -----------------------------------------------------
LAMBDA_DYN        = 1e3                  # penalty on scaled dynamics defects
LAMBDA_OBS        = 1e3                  # penalty on obstacle violations / POS_SCALE
POS_SCALE         = None                 # m; position unit for trust region/scaling
                                         #   (None = turn radius at V_CRUISE, BANK_MAX)
ETA_INIT          = 1.0                  # trust region (scaled inf-norm)
ETA_MIN           = 1e-3
ETA_MAX           = 2.0
ETA_SHRINK        = 2.0
ETA_GROW          = 2.0
RHO_0, RHO_1, RHO_2 = 0.0, 0.25, 0.7
MAX_ITERS         = 60
TOL_DECREASE_ABS  = 1e-3
TOL_DECREASE_REL  = 1e-3
TOL_STEP          = 1e-3                 # also stop when the scaled step is this small
TOL_DEFECT        = 1e-3                 # max scaled dynamics defect for success
TOL_VIOLATION     = 1e-2                 # max obstacle violation for success, m
PRUNE_BUFFER      = None                 # m, extra reach when pruning (None = POS_SCALE / 4)
                                         #   (pruned obstacles still count in the merit, so a
                                         #    step into one is corrected next iteration)

# ---- restarts ------------------------------------------------------------
N_STARTS          = 5                    # 1 = straight-line guess only
VIA_OFFSET        = (0.1, 0.4)           # via-point offset / start-goal distance
RESTART_SEED      = 0

# ---- verification --------------------------------------------------------
DENSE_STEPS       = 40                   # RK4 steps per interval in final check
DENSE_TOLERANCE   = None                 # m, allowed intrusion into safety margin
                                         #   between check points (None = 25% of env margin)
SOLVER            = "CLARABEL"


def _load_airframe():
    """Apply AIRFRAME_FILE overrides, then fill in automatic scale settings."""
    import os
    g = globals()
    if AIRFRAME_FILE and os.path.exists(AIRFRAME_FILE):
        with open(AIRFRAME_FILE) as f:
            params = json.load(f)
        for k, v in params.items():
            if k.isupper():
                g[k] = tuple(v) if isinstance(v, list) else v
        g["AIRFRAME_NAME"] = params.get("name", AIRFRAME_FILE)
    else:
        g["AIRFRAME_NAME"] = "generic small UAV"
    if g["POS_SCALE"] is None:
        g["POS_SCALE"] = g["V_CRUISE"] ** 2 / (g["GRAVITY"] * np.tan(np.radians(g["BANK_MAX_DEG"])))
    if g["PRUNE_BUFFER"] is None:
        g["PRUNE_BUFFER"] = 0.25 * g["POS_SCALE"]


_load_airframe()


# --------------------------------------------------------------------------
# aircraft model
# --------------------------------------------------------------------------
class FixedWing3DOF:
    nx, nu = 6, 3

    def __init__(self):
        self.m, self.g = MASS, GRAVITY
        self.a1 = 0.5 * RHO * WING_AREA * C_D0                           # D = a1 V^2 + a2 n^2 / V^2
        self.a2 = 2.0 * K_INDUCED * (MASS * GRAVITY) ** 2 / (RHO * WING_AREA)
        self.c_stall = RHO * WING_AREA * C_L_MAX / (2.0 * MASS * GRAVITY)  # n <= c_stall V^2

    def drag(self, V, n2):
        return self.a1 * V**2 + self.a2 * n2 / V**2

    def f(self, x, u):
        """Dynamics, batched over leading dimensions."""
        V, ga, ch = x[..., 3], x[..., 4], x[..., 5]
        T, nv, nh = u[..., 0], u[..., 1], u[..., 2]
        cg, sg, cc, sc = np.cos(ga), np.sin(ga), np.cos(ch), np.sin(ch)
        D = self.drag(V, nv**2 + nh**2)
        return np.stack([V * cg * cc, V * cg * sc, V * sg,
                         (T - D) / self.m - self.g * sg,
                         self.g * (nv - cg) / V,
                         self.g * nh / (V * cg)], axis=-1)

    def jacobians(self, x, u):
        """A = df/dx (..., 6, 6), B = df/du (..., 6, 3)."""
        V, ga, ch = x[..., 3], x[..., 4], x[..., 5]
        T, nv, nh = u[..., 0], u[..., 1], u[..., 2]
        cg, sg, cc, sc = np.cos(ga), np.sin(ga), np.cos(ch), np.sin(ch)
        g, m, n2 = self.g, self.m, nv**2 + nh**2
        A = np.zeros(x.shape[:-1] + (6, 6))
        B = np.zeros(x.shape[:-1] + (6, 3))
        A[..., 0, 3], A[..., 0, 4], A[..., 0, 5] = cg * cc, -V * sg * cc, -V * cg * sc
        A[..., 1, 3], A[..., 1, 4], A[..., 1, 5] = cg * sc, -V * sg * sc, V * cg * cc
        A[..., 2, 3], A[..., 2, 4] = sg, V * cg
        A[..., 3, 3] = -(2 * self.a1 * V - 2 * self.a2 * n2 / V**3) / m
        A[..., 3, 4] = -g * cg
        A[..., 4, 3], A[..., 4, 4] = -g * (nv - cg) / V**2, g * sg / V
        A[..., 5, 3] = -g * nh / (V**2 * cg)
        A[..., 5, 4] = g * nh * sg / (V * cg**2)
        B[..., 3, 0] = 1.0 / m
        B[..., 3, 1] = -2 * self.a2 * nv / (V**2 * m)
        B[..., 3, 2] = -2 * self.a2 * nh / (V**2 * m)
        B[..., 4, 1] = g / V
        B[..., 5, 2] = g / (V * cg)
        return A, B

    def trim_controls(self, x):
        """Controls holding speed and flight-path angle, wings level."""
        V, ga = x[..., 3], x[..., 4]
        nv = np.cos(ga)
        T_av = THRUST_PLAN_FRACTION * (T_MAX + THRUST_SLOPE * V)
        T = np.clip(self.drag(V, nv**2) + self.m * self.g * np.sin(ga), 0.0, T_av)
        return np.stack([T, nv, np.zeros_like(nv)], axis=-1)


# --------------------------------------------------------------------------
# result container (common solver interface)
# --------------------------------------------------------------------------
@dataclass
class SolveResult:
    success: bool
    status: str
    iterations: int
    solve_time: float
    flight_time: float
    cost: float
    max_defect: float
    max_violation: float
    dense_min_margin: float
    x: np.ndarray
    u: np.ndarray
    history: list = field(default_factory=list)
    attempts: list = field(default_factory=list)

    def to_dict(self):
        d = {k: getattr(self, k) for k in ("success", "status", "iterations", "solve_time",
                                            "flight_time", "cost", "max_defect",
                                            "max_violation", "dense_min_margin",
                                            "history", "attempts")}
        d["x"], d["u"] = self.x.tolist(), self.u.tolist()
        return d


# --------------------------------------------------------------------------
# solver
# --------------------------------------------------------------------------
class AircraftSCP:
    name = "aircraft_scp"

    def __init__(self, verbose=VERBOSE, n_starts=N_STARTS):
        self.model = FixedWing3DOF()
        self.verbose, self.n_starts = verbose, n_starts
        self.xs = np.array([POS_SCALE] * 3 + [V_MAX - V_MIN, 1.0, 1.0])   # state scales
        self.us = np.array([T_MAX + THRUST_SLOPE * V_MAX, N_MAX, N_MAX])   # control scales

    # ---- boundary conditions and guesses ----------------------------------
    def boundary(self, env):
        d = env.goal_pos - env.start_pos
        chi0 = np.arctan2(d[1], d[0])
        x0 = np.r_[env.start_pos, V_CRUISE, 0.0, chi0]
        return x0, env.goal_pos

    def initial_guesses(self, env):
        """Straight line first, then lines bent through a random via point.
        Override to plug in a warm start."""
        rng = np.random.default_rng(RESTART_SEED)
        a, b = env.start_pos, env.goal_pos
        lo, hi = env.position_bounds()
        dist = np.linalg.norm(b - a)
        for k in range(self.n_starts):
            if k == 0:
                pts = np.stack([a, b])
            else:
                w = rng.normal(size=3)
                w -= (w @ (b - a)) / dist**2 * (b - a)
                w *= rng.uniform(*VIA_OFFSET) * dist / np.linalg.norm(w)
                pts = np.stack([a, np.clip(a + rng.uniform(0.3, 0.7) * (b - a) + w, lo, hi), b])
            yield self._polyline_guess(pts, env)

    def _polyline_guess(self, pts, env):
        seg = np.linalg.norm(np.diff(pts, axis=0), axis=1)
        s_pts = np.r_[0.0, np.cumsum(seg)]
        s_new = np.linspace(0.0, s_pts[-1], N_NODES)
        p = np.stack([np.interp(s_new, s_pts, pts[:, k]) for k in range(3)], axis=1)
        d = np.gradient(p, axis=0)
        gam = np.clip(np.arctan2(d[:, 2], np.linalg.norm(d[:, :2], axis=1)),
                      -np.radians(GAMMA_MAX_DEG), np.radians(GAMMA_MAX_DEG))
        chi = np.unwrap(np.arctan2(d[:, 1], d[:, 0]))
        x = np.column_stack([p, np.full(N_NODES, V_CRUISE), gam, chi])
        x[0] = self.boundary(env)[0]
        u = self.model.trim_controls(x)
        sigma = float(np.clip(s_pts[-1] / V_CRUISE, *SIGMA_BOUNDS))
        return x, u, sigma

    # ---- propagation -------------------------------------------------------
    def propagate(self, X, U, sigma, steps, sens=True):
        """Integrate every interval from its start node (multiple shooting).
        Returns end states, per-substep states (K, steps, 6) and, if sens,
        sensitivities at every substep and at the end."""
        K = len(X) - 1
        dtau = 1.0 / K
        h = 1.0 / steps
        uk, uk1 = U[:-1], U[1:]
        x = X[:-1].copy()
        Phi = np.tile(np.eye(6), (K, 1, 1))
        Bm, Bp = np.zeros((K, 6, 3)), np.zeros((K, 6, 3))
        S = np.zeros((K, 6))

        def rhs(s, x, Phi, Bm, Bp, S):
            u = (1 - s) * uk + s * uk1
            fx = self.model.f(x, u)
            dx = dtau * sigma * fx
            if not sens:
                return dx, None, None, None, None
            A, B = self.model.jacobians(x, u)
            A, B = dtau * sigma * A, dtau * sigma * B
            return (dx, A @ Phi, A @ Bm + (1 - s) * B, A @ Bp + s * B,
                    np.einsum("kij,kj->ki", A, S) + dtau * fx)

        traj = {"x": [], "Phi": [], "Bm": [], "Bp": [], "S": []}
        for j in range(steps):
            s0 = j * h
            traj["x"].append(x)
            if sens:
                traj["Phi"].append(Phi); traj["Bm"].append(Bm)
                traj["Bp"].append(Bp); traj["S"].append(S)
            state = (x, Phi, Bm, Bp, S)
            k1 = rhs(s0, *state)
            k2 = rhs(s0 + h / 2, *[a + h / 2 * b if b is not None else a for a, b in zip(state, k1)])
            k3 = rhs(s0 + h / 2, *[a + h / 2 * b if b is not None else a for a, b in zip(state, k2)])
            k4 = rhs(s0 + h, *[a + h * b if b is not None else a for a, b in zip(state, k3)])
            new = []
            for a, b1, b2, b3, b4 in zip(state, k1, k2, k3, k4):
                new.append(a if b1 is None else a + h / 6 * (b1 + 2 * b2 + 2 * b3 + b4))
            x, Phi, Bm, Bp, S = new
        out = {"x_end": x, "x_sub": np.stack(traj["x"], axis=1)}
        if sens:
            out.update(Phi=Phi, Bm=Bm, Bp=Bp, S=S,
                       Phi_sub=np.stack(traj["Phi"], 1), Bm_sub=np.stack(traj["Bm"], 1),
                       Bp_sub=np.stack(traj["Bp"], 1), S_sub=np.stack(traj["S"], 1))
        return out

    # ---- merit ---------------------------------------------------------------
    def obstacle_eval(self, env, P):
        """Normalized constraint values h/||g|| (C, m) and unit normals (C, m, 3)."""
        A, b = env.linearized_constraints(P)
        h = np.einsum("cmk,ck->cm", A, P) - b
        gn = np.maximum(np.linalg.norm(A, axis=-1), 1e-9)
        return h / gn, A / gn[..., None]

    def check_points(self, X, prop):
        """Positions at every substep of every interval, plus the final node."""
        P = prop["x_sub"][..., :3].reshape(-1, 3)
        return np.vstack([P, X[-1, :3]])

    def cost(self, X, U, sigma):
        return (W_TIME * sigma
                + W_SPEED * float(np.mean(((X[:, 3] - V_CRUISE) / V_CRUISE) ** 2))
                + W_SMOOTH * float(np.sum((np.diff(U, axis=0) / self.us) ** 2)))

    def merit(self, env, X, U, sigma):
        prop = self.propagate(X, U, sigma, RK4_STEPS, sens=False)
        defect = np.abs((X[1:] - prop["x_end"]) / self.xs)
        hn, _ = self.obstacle_eval(env, self.check_points(X, prop))
        viol = np.maximum(0.0, -hn).max(axis=1)
        J = self.cost(X, U, sigma) + LAMBDA_DYN * defect.sum() + LAMBDA_OBS * viol.sum() / POS_SCALE
        return J, float(defect.max()), float(viol.max())

    # ---- main entry point --------------------------------------------------
    def solve(self, env: Environment) -> SolveResult:
        t0 = time.perf_counter()
        best, attempts = None, []
        for guess in self.initial_guesses(env):
            res = self._solve_from(env, guess)
            attempts.append(res.status)
            if best is None or res.success or \
                    res.max_violation + res.max_defect < best.max_violation + best.max_defect:
                best = res
            if res.success:
                break
        best.attempts, best.solve_time = attempts, time.perf_counter() - t0
        return best

    def _solve_from(self, env, guess):
        t0 = time.perf_counter()
        N, nx, nu = N_NODES, 6, 3
        nz = N * nx + N * nu + 1                     # z = [vec(X), vec(U), sigma]
        ix = lambda k: k * nx
        iu = lambda k: N * nx + k * nu
        isg = nz - 1
        x0, p_goal = self.boundary(env)
        lo, hi = env.position_bounds()

        X_bar, U_bar, s_bar = guess
        J_bar, def_bar, viol_bar = self.merit(env, X_bar, U_bar, s_bar)
        eta, history, status, converged = ETA_INIT, [], "max_iterations", False

        tanb = np.tan(np.radians(BANK_MAX_DEG))
        gmax = np.radians(GAMMA_MAX_DEG)
        us_row = self.us[None, :]

        it = 0
        for it in range(1, MAX_ITERS + 1):
            prop = self.propagate(X_bar, U_bar, s_bar, RK4_STEPS, sens=True)
            zbar = np.r_[X_bar.ravel(), U_bar.ravel(), s_bar]
            # The subproblem is solved for the scaled step dz = (z - zbar) / zs,
            # which keeps the numbers the solver sees small and well conditioned.
            zs = np.r_[np.tile(self.xs, N), np.tile(self.us, N), s_bar]
            dz = cp.Variable(nz)
            nu_v = cp.Variable((N - 1) * nx)                  # scaled virtual control
            X = X_bar + cp.multiply(self.xs[None, :], cp.reshape(dz[:N * nx], (N, nx), order="C"))
            U = U_bar + cp.multiply(us_row, cp.reshape(dz[N * nx:N * (nx + nu)], (N, nu), order="C"))
            sig = s_bar * (1 + dz[isg])

            cons = [X[0] == x0, X[-1, :3] == p_goal,
                    X[:, :3] >= lo, X[:, :3] <= hi,
                    X[:, 3] >= V_MIN, X[:, 3] <= V_MAX,
                    cp.abs(X[:, 4]) <= gmax,
                    U[:, 0] >= 0,
                    U[:, 0] <= THRUST_PLAN_FRACTION * (T_MAX + THRUST_SLOPE * X[:, 3]),
                    cp.norm(U[:, 1:], 2, axis=1) <= N_MAX,
                    cp.abs(U[:, 2]) <= tanb * U[:, 1],
                    sig >= SIGMA_BOUNDS[0], sig <= SIGMA_BOUNDS[1],
                    cp.abs(dz) <= (TRUST_CAP if ALGORITHM == "ptr" else eta)]   # trust region
            if FINAL_LEVEL:
                cons.append(X[-1, 4] == 0)
            # control rate limits: |u_{k+1} - u_k| <= rate * dt, with dt = sigma / (N - 1)
            for col, rate in ((1, N_V_RATE_MAX), (2, N_H_RATE_MAX)):
                if rate is not None:
                    cons.append(cp.abs(cp.diff(U[:, col])) <= rate * sig / (N - 1))
            # stall: ||n|| <= c_stall * V^2, with V^2 replaced by its tangent (conservative)
            cons.append(cp.norm(U[:, 1:], 2, axis=1) <=
                        self.model.c_stall * (2 * cp.multiply(X_bar[:, 3], X[:, 3]) - X_bar[:, 3] ** 2))

            # linearized dynamics in the step variables:
            #   dx_{k+1} - Phi dx_k - Bm du_k - Bp du_{k+1} - S dsigma - nu = x_prop - x_bar_{k+1}
            rows, cols, vals = [], [], []
            def put(r0, c0, block):
                r, c = np.nonzero(np.ones_like(block, dtype=bool))
                rows.append(r0 + r); cols.append(c0 + c); vals.append(block.ravel())
            for k in range(N - 1):
                r0 = k * nx
                put(r0, ix(k + 1), np.eye(nx))
                put(r0, ix(k), -prop["Phi"][k])
                put(r0, iu(k), -prop["Bm"][k])
                put(r0, iu(k + 1), -prop["Bp"][k])
                put(r0, isg, -prop["S"][k][:, None])
            Dm = sp.csr_matrix((np.concatenate(vals), (np.concatenate(rows), np.concatenate(cols))),
                               shape=((N - 1) * nx, nz))
            xs_rep = np.tile(self.xs, N - 1)
            Dm_s = sp.diags(1 / xs_rep) @ Dm @ sp.diags(zs)        # rows scaled by state scales
            gap = ((prop["x_end"] - X_bar[1:]) / self.xs).ravel()   # minus the scaled defect
            cons.append(Dm_s @ dz - nu_v == gap)

            # obstacle constraints at every substep, linear in the step variables:
            #   n . (dP/dz) zs dz + slack >= -h/||g||
            P_bar = self.check_points(X_bar, prop)
            C = len(P_bar)
            hn, G = self.obstacle_eval(env, P_bar)
            reach = np.sqrt(3) * (TRUST_CAP if ALGORITHM == "ptr" else eta) * POS_SCALE + PRUNE_BUFFER
            rc, rm = np.nonzero(hn <= reach)
            slack = cp.Variable(C, nonneg=True)
            if len(rc):
                Kr = len(rc)
                n_rows = G[rc, rm]                                   # (Kr, 3) unit normals
                last = rc == C - 1                                   # final node rows
                mid = ~last
                k, j = np.divmod(rc[mid], RK4_STEPS)                 # interval, substep
                r_mid = np.nonzero(mid)[0]
                nm = n_rows[mid]
                cx = np.einsum("ri,rij->rj", nm, prop["Phi_sub"][k, j][:, :3])      # (R, 6)
                cm = np.einsum("ri,rij->rj", nm, prop["Bm_sub"][k, j][:, :3])       # (R, 3)
                cp_ = np.einsum("ri,rij->rj", nm, prop["Bp_sub"][k, j][:, :3])      # (R, 3)
                cs = np.einsum("ri,ri->r", nm, prop["S_sub"][k, j][:, :3])          # (R,)
                r_last = np.nonzero(last)[0]
                rows_ = np.concatenate([np.repeat(r_mid, nx), np.repeat(r_mid, nu), np.repeat(r_mid, nu),
                                        r_mid, np.repeat(r_last, 3)])
                cols_ = np.concatenate([(ix(k)[:, None] + np.arange(nx)).ravel(),
                                        (iu(k)[:, None] + np.arange(nu)).ravel(),
                                        (iu(k + 1)[:, None] + np.arange(nu)).ravel(),
                                        np.full(len(r_mid), isg),
                                        (ix(N - 1) + np.arange(3)[None, :]).repeat(len(r_last), 0).ravel()])
                vals_ = np.concatenate([cx.ravel(), cm.ravel(), cp_.ravel(), cs, n_rows[last].ravel()])
                Gm = sp.csr_matrix((vals_, (rows_, cols_)), shape=(Kr, nz)) @ sp.diags(zs)
                Es = sp.csr_matrix((np.ones(Kr), (np.arange(Kr), rc)), shape=(Kr, C))
                cons.append(Gm @ dz + Es @ slack >= -hn[rc, rm])

            cost_expr = (W_TIME * sig
                         + W_SPEED * cp.sum_squares((X[:, 3] - V_CRUISE) / V_CRUISE) / N
                         + W_SMOOTH * cp.sum_squares(cp.multiply(cp.diff(U, axis=0), 1 / us_row)))
            L_expr = cost_expr + LAMBDA_DYN * cp.norm1(nu_v) + LAMBDA_OBS * cp.sum(slack) / POS_SCALE
            trust_pen = W_TRUST * cp.sum_squares(dz) if ALGORITHM == "ptr" else 0
            prob = cp.Problem(cp.Minimize(L_expr + trust_pen), cons)
            try:
                prob.solve(solver=SOLVER, canon_backend=cp.SCIPY_CANON_BACKEND)
                ok = prob.status in ("optimal", "optimal_inaccurate")
            except cp.error.SolverError:
                ok = False
            if not ok:
                eta /= ETA_SHRINK
                history.append({"iter": it, "eta": eta, "event": "subproblem_failed"})
                if eta < ETA_MIN:
                    status = "solver_error"
                    break
                continue

            zv = zbar + zs * dz.value
            X_new = zv[:N * nx].reshape(N, nx)
            U_new = zv[N * nx:N * (nx + nu)].reshape(N, nu)
            s_new = float(zv[isg])
            L_new = float(L_expr.value)
            J_new, def_new, viol_new = self.merit(env, X_new, U_new, s_new)
            predicted, actual = J_bar - L_new, J_bar - J_new
            rho = actual / predicted if predicted > 1e-12 else 1.0
            rec = {"iter": it, "J": J_new, "L": L_new, "flight_time": s_new,
                   "max_defect": def_new, "max_violation": viol_new,
                   "rho": rho, "eta": eta, "n_obstacle_rows": int(len(rc))}

            step = max(np.max(np.abs(X_new - X_bar) / self.xs), np.max(np.abs(U_new - U_bar) / self.us),
                       abs(s_new - s_bar) / s_bar)
            rec["step"] = float(step)
            if ALGORITHM == "ptr":
                improvement = J_bar - J_new
                X_bar, U_bar, s_bar, J_bar, def_bar, viol_bar = X_new, U_new, s_new, J_new, def_new, viol_new
                rec["event"] = "accepted"
                history.append(rec)
                if self.verbose:
                    print(f"    it {it:2d}  J {J_new:10.3f}  tf {s_new:6.1f}s  defect {def_new:.1e}  "
                          f"viol {viol_new:.1e}  step {step:.1e}")
                small = step <= TOL_STEP or 0 <= improvement <= TOL_DECREASE_ABS + TOL_DECREASE_REL * abs(J_new)
                if small and def_new <= TOL_DEFECT and viol_new <= TOL_VIOLATION:
                    rec["event"] = "converged"
                    converged = True
                    break
                continue

            if predicted <= TOL_DECREASE_ABS + TOL_DECREASE_REL * abs(J_bar) or step <= TOL_STEP:
                if J_new <= J_bar:
                    X_bar, U_bar, s_bar, J_bar, def_bar, viol_bar = X_new, U_new, s_new, J_new, def_new, viol_new
                rec["event"] = "converged"
                history.append(rec)
                converged = True
                break
            if rho < RHO_0:
                eta /= ETA_SHRINK
                rec["event"] = "rejected"
            else:
                X_bar, U_bar, s_bar, J_bar, def_bar, viol_bar = X_new, U_new, s_new, J_new, def_new, viol_new
                if rho < RHO_1:
                    eta /= ETA_SHRINK
                elif rho >= RHO_2:
                    eta = min(eta * ETA_GROW, ETA_MAX)
                rec["event"] = "accepted"
            history.append(rec)
            if self.verbose:
                print(f"    it {it:2d}  J {J_new:10.3f}  tf {s_new:6.1f}s  defect {def_new:.1e}  "
                      f"viol {viol_new:.1e}  rho {rho:6.2f}  eta {eta:.3f}  {rec['event']}")
            if eta < ETA_MIN:
                status = "trust_region_collapsed"
                break

        # ---- classify and verify -------------------------------------------
        dense = self.propagate(X_bar, U_bar, s_bar, DENSE_STEPS, sens=False)
        margin = float(self.obstacle_eval(env, self.check_points(X_bar, dense))[0].min())
        dense_tol = DENSE_TOLERANCE if DENSE_TOLERANCE is not None else 0.25 * env.margin
        feasible = def_bar <= TOL_DEFECT and viol_bar <= TOL_VIOLATION
        if feasible and margin < -dense_tol:
            status = "dense_check_failed"
        elif feasible:
            # a dynamically feasible, collision-free trajectory; if SCP stopped
            # early (e.g. trust region collapsed) it may not be fully optimal
            status = "feasible" if converged else "feasible_unconverged"
        elif converged:
            status = "converged_infeasible"
        return SolveResult(status.startswith("feasible"), status, it, time.perf_counter() - t0, s_bar,
                           self.cost(X_bar, U_bar, s_bar), def_bar, viol_bar, margin, X_bar, U_bar, history)


# --------------------------------------------------------------------------
# plotting
# --------------------------------------------------------------------------
def load_plan(envs_file, results_file, index):
    """Load environment `index` and its saved SCP result, refusing to pair a
    plan with an environment it was not solved for."""
    from types import SimpleNamespace
    envs = load_environments(envs_file)
    with open(results_file) as f:
        r = next((r for r in json.load(f) if r["env_index"] == index), None)
    if r is None:
        raise SystemExit(f"No result for environment {index} in {results_file}.")
    if index >= len(envs):
        raise SystemExit(f"{envs_file} has only {len(envs)} environments.")
    env = envs[index]
    fp = r.get("env_fingerprint")
    if fp is None:
        print(f"Warning: {results_file} predates environment fingerprints; cannot confirm it "
              f"was solved on {envs_file}. Re-run scp_aircraft.py to be safe.")
    elif fp != env.fingerprint():
        raise SystemExit(
            f"MISMATCH: the plan for environment {index} in {results_file} was solved on a different "
            f"environment (it came from {r.get('env_file', '?')}) than environment {index} in {envs_file}.\n"
            f"Pass the same --envs file that was used when solving, or re-run scp_aircraft.py.")
    res = SimpleNamespace(x=np.array(r["x"]), u=np.array(r["u"]), flight_time=r["flight_time"],
                          status=r["status"], success=r["success"])
    return env, r, res


def plan_clearance(env, res, solver=None, steps=40):
    """Closest approach of the planned path to any obstacle surface, allowing
    for the vehicle radius (negative = the aircraft would touch it)."""
    solver = solver or AircraftSCP()
    dense = solver.propagate(np.asarray(res.x), np.asarray(res.u), res.flight_time, steps, sens=False)
    P = solver.check_points(np.asarray(res.x), dense)
    A, b = env.linearized_constraints(P)
    h = np.einsum("cmk,ck->cm", A, P) - b                     # at d = r + margin
    gn = np.maximum(np.linalg.norm(A, axis=-1), 1e-9)
    return float((h / gn).min() + env.margin)                  # add back the margin -> body clearance


def plot_result(env, res, solver):
    import matplotlib.pyplot as plt
    from envgen import plot_environment

    dense = solver.propagate(res.x, res.u, res.flight_time, 20, sens=False)
    P = solver.check_points(res.x, dense)
    ax = plot_environment(env)
    ax.plot(P[:, 0], P[:, 1], P[:, 2], "k-", lw=2, label=f"SCP ({res.status})")
    ax.legend(loc="upper left")

    t = np.linspace(0, res.flight_time, len(res.x))
    bank = np.degrees(np.arctan2(res.u[:, 2], res.u[:, 1]))
    fig, axs = plt.subplots(2, 2, figsize=(10, 6), sharex=True)
    axs[0, 0].plot(t, res.x[:, 3]); axs[0, 0].axhline(V_MIN, ls=":", c="r"); axs[0, 0].set_ylabel("V [m/s]")
    axs[0, 1].plot(t, np.degrees(res.x[:, 4])); axs[0, 1].set_ylabel("gamma [deg]")
    axs[1, 0].plot(t, bank); axs[1, 0].set_ylabel("bank [deg]"); axs[1, 0].set_xlabel("t [s]")
    axs[1, 1].plot(t, res.u[:, 0]); axs[1, 1].set_ylabel("thrust [N]"); axs[1, 1].set_xlabel("t [s]")
    fig.tight_layout()
    plt.show()


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser(description="Run fixed-wing SCP on generated environments.")
    ap.add_argument("--envs", default=ENV_FILE)
    ap.add_argument("--out", default=RESULTS_FILE)
    ap.add_argument("--feasible-out", default=FEASIBLE_FILE)
    ap.add_argument("--max-envs", type=int, default=MAX_ENVS)
    ap.add_argument("--plot", type=int, default=PLOT_INDEX, metavar="INDEX",
                    help="solve, then re-solve and plot this environment")
    ap.add_argument("--show", type=int, default=None, metavar="INDEX",
                    help="plot a SAVED result (from --out) without solving anything")
    ap.add_argument("--verbose", action=argparse.BooleanOptionalAction, default=VERBOSE)
    args = ap.parse_args()
    warnings.filterwarnings("ignore", category=UserWarning, module="cvxpy")

    if args.show is not None:
        env, r, res = load_plan(args.envs, args.out, args.show)
        print(f"Environment {args.show}: {res.status}, flight {res.flight_time:.1f} s, "
              f"closest approach to an obstacle {plan_clearance(env, res):.1f} m")
        plot_result(env, res, AircraftSCP())
        return

    envs = load_environments(args.envs)[: args.max_envs]
    solver = AircraftSCP(verbose=args.verbose)
    results, feasible = [], []
    print(f"Solving {len(envs)} environments with {solver.name} [{AIRFRAME_NAME}] "
          f"(up to {solver.n_starts} starts each)")
    for i, env in enumerate(envs):
        res = solver.solve(env)
        print(f"  env {i:3d}  fill {env.metrics.get('occupancy_fraction', float('nan')):5.1%}  "
              f"{res.status:24s} start {len(res.attempts)}  iters {res.iterations:2d}  "
              f"{res.solve_time:6.1f}s  flight {res.flight_time:6.1f}s  margin {res.dense_min_margin:+.2f}")
        results.append({"env_index": i, "env_file": args.envs, "env_fingerprint": env.fingerprint(),
                        "solver": solver.name, **res.to_dict()})
        if res.success:
            feasible.append(env)

    with open(args.out, "w") as f:
        json.dump(results, f)
    save_environments(feasible, args.feasible_out)
    print(f"\n{len(feasible)}/{len(envs)} feasible. Results -> {args.out}, "
          f"feasible environments -> {args.feasible_out}")
    if args.plot is not None:
        plot_result(envs[args.plot], solver.solve(envs[args.plot]), solver)


if __name__ == "__main__":
    main()